#!/usr/bin/env bash

# Description: Open all files under selection in you editor
#
# Note: Works _only_ with selection
#
# Shell: POSIX compliant
# Author: Akshit Anand

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    xargs -0 "$EDITOR" < "$selection"

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
fi
