#!/usr/bin/env bash

# Description: Search for all the directories in $HOME and cd there in CTX
# Dependencies: fzf, fd
# Shell: >= bash
# Author: Akshit Anand

. "$(dirname "$0")"/.nnn-plugin-helper
CTX=1

dir=$(fd --type directory --base-directory "$HOME" | fzf) || exit

dir="$HOME/$dir"
[[ -d "$dir" ]] && nnn_cd "$dir" "$CTX"
