#!/usr/bin/env bash

FPATH="$1"

if [ -z "$FPATH" ]; then
    exit 0
fi

selected_cmd=$(j4-dmenu-desktop --dmenu="fzf" --no-exec --no-generic 2>/dev/null)

if [ -n "$selected_cmd" ]; then
    eval $selected_cmd $FPATH 2>/dev/null &
fi
