#!/usr/bin/env bash

. "$(dirname "$0")/.nnn-plugin-helper"

text_files=()
other_files=()

categorize_file() {
    local f="$1"
    case $(file --mime-type -Lb -- "$f") in
        text/*) text_files+=("$f") ;;
        *)      other_files+=("$f") ;;
    esac
}

if [ "$(cmd_exists file)" -ne 0 ]; then
    echo "smart-open: 'file' command not found" 1>&2
    exit 1
fi

if nnn_use_selection "Open"; then
    while IFS= read -r -d '' f || [ -n "$f" ]; do
        [ -n "$f" ] && categorize_file "$f"
    done < "$selection"
elif [ -n "$1" ]; then
    if [ -d "$1" ]; then
        nnn_cd "$1"
        exit 0
    fi
    categorize_file "$1"
else
    exit 0
fi

for f in "${other_files[@]}"; do
    ${OPENER:-xdg-open} "$f" > /dev/null 2>&1 &
done

if [ ${#text_files[@]} -gt 0 ]; then
    ${EDITOR:-vi} "${text_files[@]}"
fi

if [ -p "$NNN_PIPE" ]; then
    printf "-" > "$NNN_PIPE"
fi
